FROM java:8-alpine
## 设置时区
RUN apk add -U tzdata
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
## 设置输出格式
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

MAINTAINER saleson
ADD istio-springboot-demo-a-1.0-SNAPSHOT.jar demo-a-app.jar
EXPOSE 8080
#ENTRYPOINT ["java", "-Xmx32M ", "-Xms32M", "-Xmn32M", "-Xss256K","-jar","demo-a-app.jar", "--spring.profiles.active=dev"]

ENTRYPOINT exec java -Xmx32m -Xms32m -Xmn32m -Xss256k -jar demo-a-app.jar --spring.profiles.active=dev
# ENTRYPOINT ["java","-jar","demo-a-app.jar"]
#CMD java  -Xmx32m -Xms32m -Xmn32m -Xss256k -Djava.security.egd=file:/dev/./urandom -Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF8 -Duser.timezone=GMT+8 -jar demo-a-app.jar --spring.profiles.active=dev
# CMD java -Xmx32m -Xms32m -Xmn32m -Xss256k -jar demo-a-app.jar --spring.profiles.active=dev